import type { AppLocale } from "./i18n-config";

/** UI grouping (not strict UN regions). */
export const CONTINENT_KEYS = [
  "americas",
  "europe",
  "africa",
  "asia",
  "oceania",
  "mena",
] as const;

export type ContinentKey = (typeof CONTINENT_KEYS)[number];

type CountryRow = { iso: string; languages: readonly AppLocale[] };

/**
 * Countries in the picker; `languages` are FertilityOS locales visitors may choose
 * (filtered at runtime by `getApprovedLocales()`).
 */
export const COUNTRIES_BY_CONTINENT: Record<ContinentKey, CountryRow[]> = {
  americas: [
    { iso: "US", languages: ["en", "es"] },
    { iso: "CA", languages: ["en", "es", "fr"] },
    { iso: "HT", languages: ["fr", "en"] },
    { iso: "MX", languages: ["es", "en"] },
    { iso: "BR", languages: ["es", "en"] },
    { iso: "AR", languages: ["es", "en"] },
    { iso: "CO", languages: ["es", "en"] },
    { iso: "CL", languages: ["es", "en"] },
    { iso: "PE", languages: ["es", "en"] },
    { iso: "VE", languages: ["es", "en"] },
    { iso: "EC", languages: ["es", "en"] },
    { iso: "GT", languages: ["es", "en"] },
    { iso: "CU", languages: ["es", "en"] },
    { iso: "DO", languages: ["es", "en"] },
    { iso: "HN", languages: ["es", "en"] },
    { iso: "PY", languages: ["es", "en"] },
    { iso: "CR", languages: ["es", "en"] },
    { iso: "PA", languages: ["es", "en"] },
    { iso: "UY", languages: ["es", "en"] },
    { iso: "BO", languages: ["es", "en"] },
    { iso: "JM", languages: ["en"] },
    { iso: "TT", languages: ["en"] },
  ],
  europe: [
    { iso: "GB", languages: ["en"] },
    { iso: "IE", languages: ["en"] },
    { iso: "ES", languages: ["es", "en"] },
    { iso: "PT", languages: ["es", "en"] },
    { iso: "FR", languages: ["fr", "en", "es"] },
    { iso: "DE", languages: ["en"] },
    { iso: "IT", languages: ["en"] },
    { iso: "NL", languages: ["en"] },
    { iso: "BE", languages: ["fr", "en", "es"] },
    { iso: "CH", languages: ["fr", "en"] },
    { iso: "LU", languages: ["fr", "en"] },
    { iso: "AT", languages: ["en"] },
    { iso: "SE", languages: ["en"] },
    { iso: "NO", languages: ["en"] },
    { iso: "DK", languages: ["en"] },
    { iso: "FI", languages: ["en"] },
    { iso: "PL", languages: ["en"] },
    { iso: "CZ", languages: ["en"] },
    { iso: "RO", languages: ["en"] },
    { iso: "GR", languages: ["en"] },
    { iso: "HU", languages: ["en"] },
    { iso: "UA", languages: ["en"] },
    { iso: "RU", languages: ["en"] },
    { iso: "TR", languages: ["en", "ar"] },
  ],
  africa: [
    { iso: "NG", languages: ["en"] },
    { iso: "ZA", languages: ["en"] },
    { iso: "KE", languages: ["en"] },
    { iso: "GH", languages: ["en"] },
    { iso: "TZ", languages: ["en"] },
    { iso: "UG", languages: ["en"] },
    { iso: "ET", languages: ["en"] },
    { iso: "ZW", languages: ["en"] },
    { iso: "AO", languages: ["en"] },
    { iso: "MZ", languages: ["en"] },
    { iso: "MA", languages: ["ar", "fr", "en", "es"] },
    { iso: "DZ", languages: ["ar", "fr", "en"] },
    { iso: "TN", languages: ["ar", "fr", "en"] },
    { iso: "LY", languages: ["ar", "en"] },
    { iso: "SD", languages: ["ar", "en"] },
    { iso: "SN", languages: ["en"] },
    { iso: "CI", languages: ["en"] },
    { iso: "CM", languages: ["en"] },
    { iso: "EG", languages: ["ar", "en"] },
  ],
  asia: [
    { iso: "JP", languages: ["en"] },
    { iso: "KR", languages: ["en"] },
    { iso: "CN", languages: ["en"] },
    { iso: "IN", languages: ["en"] },
    { iso: "ID", languages: ["en"] },
    { iso: "TH", languages: ["en"] },
    { iso: "VN", languages: ["en"] },
    { iso: "PH", languages: ["en"] },
    { iso: "MY", languages: ["en"] },
    { iso: "SG", languages: ["en"] },
    { iso: "PK", languages: ["en", "ar"] },
    { iso: "BD", languages: ["en"] },
    { iso: "LK", languages: ["en"] },
    { iso: "NP", languages: ["en"] },
    { iso: "KZ", languages: ["en"] },
    { iso: "UZ", languages: ["en"] },
    { iso: "IQ", languages: ["ar", "en"] },
    { iso: "IR", languages: ["en", "ar"] },
    { iso: "AF", languages: ["en"] },
  ],
  oceania: [
    { iso: "AU", languages: ["en"] },
    { iso: "NZ", languages: ["en"] },
    { iso: "FJ", languages: ["en"] },
    { iso: "PG", languages: ["en"] },
    { iso: "PF", languages: ["fr", "en"] },
    { iso: "NC", languages: ["fr", "en"] },
  ],
  mena: [
    { iso: "SA", languages: ["ar", "en"] },
    { iso: "AE", languages: ["ar", "en"] },
    { iso: "QA", languages: ["ar", "en"] },
    { iso: "KW", languages: ["ar", "en"] },
    { iso: "BH", languages: ["ar", "en"] },
    { iso: "OM", languages: ["ar", "en"] },
    { iso: "YE", languages: ["ar", "en"] },
    { iso: "JO", languages: ["ar", "en"] },
    { iso: "LB", languages: ["ar", "fr", "en"] },
    { iso: "SY", languages: ["ar", "en"] },
    { iso: "PS", languages: ["ar", "en"] },
    { iso: "IL", languages: ["en", "ar"] },
  ],
};
