-- IVF Platform - Lab Module Database Schema (All UUID)

CREATE TABLE IF NOT EXISTS semen_samples (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    clinic_id UUID REFERENCES clinics(id) ON DELETE CASCADE,
    patient_id UUID REFERENCES patients(id) ON DELETE CASCADE,
    cycle_id UUID REFERENCES ivf_cycles(id) ON DELETE SET NULL,
    sample_number VARCHAR(50) UNIQUE NOT NULL,
    collection_date DATE NOT NULL,
    collection_time TIME,
    collection_method VARCHAR(50) DEFAULT 'masturbation',
    abstinence_days INTEGER,
    volume_ml DECIMAL(5,2),
    ph DECIMAL(3,1),
    liquefaction_time_min INTEGER,
    appearance VARCHAR(50),
    viscosity VARCHAR(20),
    concentration_million_per_ml DECIMAL(10,2),
    total_sperm_count_million DECIMAL(10,2),
    progressive_motility_percent DECIMAL(5,2),
    non_progressive_motility_percent DECIMAL(5,2),
    immotile_percent DECIMAL(5,2),
    total_motility_percent DECIMAL(5,2),
    normal_morphology_percent DECIMAL(5,2),
    head_defects_percent DECIMAL(5,2),
    midpiece_defects_percent DECIMAL(5,2),
    tail_defects_percent DECIMAL(5,2),
    vitality_percent DECIMAL(5,2),
    round_cells_million_per_ml DECIMAL(10,2),
    wbc_million_per_ml DECIMAL(10,2),
    processing_method VARCHAR(50),
    processing_notes TEXT,
    post_wash_volume_ml DECIMAL(5,2),
    post_wash_concentration DECIMAL(10,2),
    post_wash_motility_percent DECIMAL(5,2),
    post_wash_total_motile_count DECIMAL(10,2),
    sample_quality VARCHAR(20),
    diagnosis VARCHAR(100),
    used_for VARCHAR(50),
    analyzed_by UUID REFERENCES users(id),
    processed_by UUID REFERENCES users(id),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS oocyte_retrievals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    clinic_id UUID REFERENCES clinics(id) ON DELETE CASCADE,
    patient_id UUID REFERENCES patients(id) ON DELETE CASCADE,
    cycle_id UUID REFERENCES ivf_cycles(id) ON DELETE CASCADE,
    retrieval_number VARCHAR(50) UNIQUE NOT NULL,
    retrieval_date DATE NOT NULL,
    retrieval_time TIME,
    total_follicles_aspirated INTEGER DEFAULT 0,
    total_oocytes_retrieved INTEGER DEFAULT 0,
    mii_count INTEGER DEFAULT 0,
    mi_count INTEGER DEFAULT 0,
    gv_count INTEGER DEFAULT 0,
    degenerated_count INTEGER DEFAULT 0,
    abnormal_count INTEGER DEFAULT 0,
    anesthesia_type VARCHAR(50),
    procedure_duration_min INTEGER,
    complications TEXT,
    insemination_method VARCHAR(20),
    insemination_time TIME,
    sperm_source VARCHAR(50),
    semen_sample_id UUID REFERENCES semen_samples(id),
    retrieved_by UUID REFERENCES users(id),
    embryologist_id UUID REFERENCES users(id),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS oocytes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    clinic_id UUID REFERENCES clinics(id) ON DELETE CASCADE,
    retrieval_id UUID REFERENCES oocyte_retrievals(id) ON DELETE CASCADE,
    oocyte_number VARCHAR(20) NOT NULL,
    dish_position VARCHAR(20),
    maturity VARCHAR(10) NOT NULL,
    morphology_grade VARCHAR(10),
    zona_thickness VARCHAR(20),
    polar_body VARCHAR(20),
    cytoplasm VARCHAR(50),
    perivitelline_space VARCHAR(20),
    shape VARCHAR(20),
    fertilization_checked BOOLEAN DEFAULT FALSE,
    fertilization_time TIMESTAMP,
    fertilization_status VARCHAR(20),
    pronuclei_count INTEGER,
    polar_bodies_count INTEGER,
    status VARCHAR(20) DEFAULT 'retrieved',
    embryo_id UUID,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lab_embryos (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    clinic_id UUID REFERENCES clinics(id) ON DELETE CASCADE,
    patient_id UUID REFERENCES patients(id) ON DELETE CASCADE,
    cycle_id UUID REFERENCES ivf_cycles(id) ON DELETE CASCADE,
    retrieval_id UUID REFERENCES oocyte_retrievals(id),
    oocyte_id UUID REFERENCES oocytes(id),
    embryo_number VARCHAR(20) NOT NULL,
    embryo_code VARCHAR(50) UNIQUE NOT NULL,
    oocyte_source VARCHAR(20) DEFAULT 'self',
    sperm_source VARCHAR(20) DEFAULT 'partner',
    fertilization_method VARCHAR(10),
    fertilization_date DATE,
    fertilization_time TIME,
    current_day INTEGER DEFAULT 0,
    current_stage VARCHAR(30),
    current_grade VARCHAR(20),
    is_arrested BOOLEAN DEFAULT FALSE,
    arrest_day INTEGER,
    outcome VARCHAR(30),
    outcome_date DATE,
    transfer_id UUID,
    transfer_date DATE,
    freeze_id UUID,
    freeze_date DATE,
    biopsy_performed BOOLEAN DEFAULT FALSE,
    biopsy_date DATE,
    biopsy_result VARCHAR(50),
    pgt_report TEXT,
    quality_score INTEGER,
    transfer_priority INTEGER,
    created_by UUID REFERENCES users(id),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS embryo_assessments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    clinic_id UUID REFERENCES clinics(id) ON DELETE CASCADE,
    embryo_id UUID REFERENCES lab_embryos(id) ON DELETE CASCADE,
    assessment_day INTEGER NOT NULL,
    assessment_date DATE NOT NULL,
    assessment_time TIME,
    hours_post_fertilization INTEGER,
    cell_count INTEGER,
    fragmentation_percent INTEGER,
    symmetry VARCHAR(20),
    multinucleation BOOLEAN DEFAULT FALSE,
    compaction VARCHAR(20),
    cleavage_grade VARCHAR(10),
    morula_grade VARCHAR(10),
    blastocyst_expansion VARCHAR(20),
    icm_grade VARCHAR(5),
    te_grade VARCHAR(5),
    blastocyst_grade VARCHAR(10),
    expansion_score INTEGER,
    icm_score VARCHAR(5),
    te_score VARCHAR(5),
    zona_status VARCHAR(30),
    cytoplasm_quality VARCHAR(30),
    vacuoles BOOLEAN DEFAULT FALSE,
    development_status VARCHAR(30),
    quality_category VARCHAR(20),
    suitable_for_transfer BOOLEAN DEFAULT TRUE,
    suitable_for_freeze BOOLEAN DEFAULT TRUE,
    assessed_by UUID REFERENCES users(id),
    notes TEXT,
    image_path VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cryo_tanks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    clinic_id UUID REFERENCES clinics(id) ON DELETE CASCADE,
    tank_name VARCHAR(50) NOT NULL,
    tank_code VARCHAR(20) UNIQUE NOT NULL,
    tank_type VARCHAR(30),
    location VARCHAR(100),
    capacity_liters DECIMAL(10,2),
    last_nitrogen_fill DATE,
    next_fill_due DATE,
    temperature_celsius DECIMAL(5,2),
    status VARCHAR(20) DEFAULT 'active',
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cryo_canisters (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    clinic_id UUID REFERENCES clinics(id) ON DELETE CASCADE,
    tank_id UUID REFERENCES cryo_tanks(id) ON DELETE CASCADE,
    canister_name VARCHAR(50) NOT NULL,
    canister_code VARCHAR(20) NOT NULL,
    position_in_tank VARCHAR(20),
    total_canes INTEGER DEFAULT 0,
    used_canes INTEGER DEFAULT 0,
    status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(tank_id, canister_code)
);

CREATE TABLE IF NOT EXISTS cryo_canes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    clinic_id UUID REFERENCES clinics(id) ON DELETE CASCADE,
    canister_id UUID REFERENCES cryo_canisters(id) ON DELETE CASCADE,
    cane_code VARCHAR(20) NOT NULL,
    cane_color VARCHAR(20),
    position_in_canister VARCHAR(10),
    total_goblets INTEGER DEFAULT 0,
    used_goblets INTEGER DEFAULT 0,
    status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(canister_id, cane_code)
);

CREATE TABLE IF NOT EXISTS cryo_preservation (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    clinic_id UUID REFERENCES clinics(id) ON DELETE CASCADE,
    patient_id UUID REFERENCES patients(id) ON DELETE CASCADE,
    cycle_id UUID REFERENCES ivf_cycles(id),
    freeze_code VARCHAR(50) UNIQUE NOT NULL,
    freeze_date DATE NOT NULL,
    freeze_time TIME,
    specimen_type VARCHAR(30) NOT NULL,
    total_specimens INTEGER NOT NULL,
    specimens_per_device INTEGER,
    total_devices INTEGER,
    freeze_method VARCHAR(30),
    device_type VARCHAR(30),
    media_used VARCHAR(100),
    tank_id UUID REFERENCES cryo_tanks(id),
    canister_id UUID REFERENCES cryo_canisters(id),
    cane_id UUID REFERENCES cryo_canes(id),
    goblet_position VARCHAR(20),
    specific_location VARCHAR(100),
    quality_at_freeze VARCHAR(50),
    grade_at_freeze VARCHAR(20),
    embryo_ids UUID[],
    embryo_day INTEGER,
    embryo_stages TEXT,
    oocyte_ids UUID[],
    maturity_at_freeze VARCHAR(20),
    semen_sample_id UUID REFERENCES semen_samples(id),
    post_thaw_expected_motility DECIMAL(5,2),
    consent_signed BOOLEAN DEFAULT TRUE,
    consent_expiry_date DATE,
    storage_duration_years INTEGER,
    frozen_by UUID REFERENCES users(id),
    witnessed_by UUID REFERENCES users(id),
    status VARCHAR(20) DEFAULT 'stored',
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cryo_thaw (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    clinic_id UUID REFERENCES clinics(id) ON DELETE CASCADE,
    freeze_id UUID REFERENCES cryo_preservation(id) ON DELETE CASCADE,
    thaw_code VARCHAR(50) UNIQUE NOT NULL,
    thaw_date DATE NOT NULL,
    thaw_time TIME,
    specimens_thawed INTEGER NOT NULL,
    devices_thawed INTEGER,
    specimens_survived INTEGER,
    survival_rate_percent DECIMAL(5,2),
    quality_post_thaw VARCHAR(50),
    grade_post_thaw VARCHAR(20),
    post_thaw_motility DECIMAL(5,2),
    post_thaw_concentration DECIMAL(10,2),
    expansion_post_thaw VARCHAR(30),
    re_expansion_time_hours DECIMAL(5,2),
    used_for VARCHAR(30),
    transfer_id UUID,
    thawed_by UUID REFERENCES users(id),
    witnessed_by UUID REFERENCES users(id),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_semen_samples_patient ON semen_samples(patient_id);
CREATE INDEX IF NOT EXISTS idx_semen_samples_clinic ON semen_samples(clinic_id);
CREATE INDEX IF NOT EXISTS idx_oocyte_retrievals_patient ON oocyte_retrievals(patient_id);
CREATE INDEX IF NOT EXISTS idx_oocyte_retrievals_clinic ON oocyte_retrievals(clinic_id);
CREATE INDEX IF NOT EXISTS idx_oocytes_retrieval ON oocytes(retrieval_id);
CREATE INDEX IF NOT EXISTS idx_lab_embryos_patient ON lab_embryos(patient_id);
CREATE INDEX IF NOT EXISTS idx_lab_embryos_clinic ON lab_embryos(clinic_id);
CREATE INDEX IF NOT EXISTS idx_embryo_assessments_embryo ON embryo_assessments(embryo_id);
CREATE INDEX IF NOT EXISTS idx_cryo_preservation_patient ON cryo_preservation(patient_id);
CREATE INDEX IF NOT EXISTS idx_cryo_thaw_freeze ON cryo_thaw(freeze_id);
