/**
 * FertilityOS Role-Based Access Control Configuration
 * 
 * Defines all available roles, their permissions, and module access
 * for a comprehensive fertility clinic management system
 */

// All available roles in a fertility clinic
const ROLES = {
    // Clinic Owner/Admin - Full access
    OWNER: 'owner',
    ADMIN: 'admin',
    
    // Clinical Staff
    PHYSICIAN: 'physician',
    PHYSICIAN_ASSISTANT: 'physician_assistant',
    IVF_SPECIALIST: 'ivf_specialist',
    
    // Embryology Team
    CLINICAL_EMBRYOLOGIST: 'clinical_embryologist',
    SENIOR_EMBRYOLOGIST: 'senior_embryologist',
    
    // Nursing Staff
    NURSE: 'nurse',
    NURSE_COORDINATOR: 'nurse_coordinator',
    
    // Laboratory Staff
    LAB_TECHNICIAN: 'lab_technician',
    LAB_DIRECTOR: 'lab_director',
    PATHOLOGIST: 'pathologist',
    
    // Radiology Staff
    RADIOLOGIST: 'radiologist',
    RADIOLOGY_TECHNICIAN: 'radiology_technician',
    
    // Front Office
    RECEPTIONIST: 'receptionist',
    PATIENT_COORDINATOR: 'patient_coordinator',
    
    // Finance & Billing
    FINANCE_MANAGER: 'finance_manager',
    BILLING_SPECIALIST: 'billing_specialist',
    
    // Pharmacy
    PHARMACIST: 'pharmacist',
    
    // Quality & Compliance
    QUALITY_MANAGER: 'quality_manager',
    
    // Counseling
    FERTILITY_COUNSELOR: 'fertility_counselor',
    
    // IT & Support
    IT_ADMIN: 'it_admin'
};

// All available modules in the system
const MODULES = {
    // Core Modules
    DASHBOARD: 'dashboard',
    PATIENTS: 'patients',
    APPOINTMENTS: 'appointments',
    
    // Clinical Modules
    MEDICAL_RECORDS: 'medical_records',
    CONSULTATIONS: 'consultations',
    TREATMENT_PLANS: 'treatment_plans',
    
    // IVF Specific
    IVF_CYCLES: 'ivf_cycles',
    EMBRYOLOGY: 'embryology',
    CRYOPRESERVATION: 'cryopreservation',
    STIMULATION: 'stimulation',
    
    // Laboratory
    LAB_MANAGEMENT: 'lab_management',
    LAB_TESTS: 'lab_tests',
    SEMEN_ANALYSIS: 'semen_analysis',
    
    // Radiology
    RADIOLOGY: 'radiology',
    ULTRASOUND: 'ultrasound',
    
    // Pharmacy
    PHARMACY: 'pharmacy',
    MEDICATIONS: 'medications',
    PRESCRIPTIONS: 'prescriptions',
    
    // Finance & Billing
    FINANCE: 'finance',
    BILLING: 'billing',
    INVOICES: 'invoices',
    PAYMENTS: 'payments',
    INSURANCE: 'insurance',
    
    // Inventory & Assets
    INVENTORY: 'inventory',
    ASSETS: 'assets',
    
    // Documents
    DOCUMENTS: 'documents',
    CONSENT_FORMS: 'consent_forms',
    
    // Reports & Analytics
    REPORTS: 'reports',
    ANALYTICS: 'analytics',
    
    // Administration
    USER_MANAGEMENT: 'user_management',
    CLINIC_SETTINGS: 'clinic_settings',
    SUBSCRIPTION: 'subscription',
    AUDIT_LOGS: 'audit_logs'
};

// Permission levels
const PERMISSIONS = {
    VIEW: 'view',
    CREATE: 'create',
    EDIT: 'edit',
    DELETE: 'delete',
    FULL: 'full', // All permissions
    NONE: 'none'
};

// Role permissions mapping - defines what each role can access
const ROLE_PERMISSIONS = {
    [ROLES.OWNER]: {
        description: 'Clinic Owner - Full system access',
        displayName: 'Clinic Owner',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.FULL,
            [MODULES.PATIENTS]: PERMISSIONS.FULL,
            [MODULES.APPOINTMENTS]: PERMISSIONS.FULL,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.FULL,
            [MODULES.CONSULTATIONS]: PERMISSIONS.FULL,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.FULL,
            [MODULES.IVF_CYCLES]: PERMISSIONS.FULL,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.FULL,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.FULL,
            [MODULES.STIMULATION]: PERMISSIONS.FULL,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.FULL,
            [MODULES.LAB_TESTS]: PERMISSIONS.FULL,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.FULL,
            [MODULES.RADIOLOGY]: PERMISSIONS.FULL,
            [MODULES.ULTRASOUND]: PERMISSIONS.FULL,
            [MODULES.PHARMACY]: PERMISSIONS.FULL,
            [MODULES.MEDICATIONS]: PERMISSIONS.FULL,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.FULL,
            [MODULES.FINANCE]: PERMISSIONS.FULL,
            [MODULES.BILLING]: PERMISSIONS.FULL,
            [MODULES.INVOICES]: PERMISSIONS.FULL,
            [MODULES.PAYMENTS]: PERMISSIONS.FULL,
            [MODULES.INSURANCE]: PERMISSIONS.FULL,
            [MODULES.INVENTORY]: PERMISSIONS.FULL,
            [MODULES.ASSETS]: PERMISSIONS.FULL,
            [MODULES.DOCUMENTS]: PERMISSIONS.FULL,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.FULL,
            [MODULES.REPORTS]: PERMISSIONS.FULL,
            [MODULES.ANALYTICS]: PERMISSIONS.FULL,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.FULL,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.FULL,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.FULL,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.FULL
        }
    },
    
    [ROLES.ADMIN]: {
        description: 'Clinic Administrator - Full access except subscription',
        displayName: 'Administrator',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.FULL,
            [MODULES.PATIENTS]: PERMISSIONS.FULL,
            [MODULES.APPOINTMENTS]: PERMISSIONS.FULL,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.VIEW,
            [MODULES.CONSULTATIONS]: PERMISSIONS.VIEW,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.VIEW,
            [MODULES.IVF_CYCLES]: PERMISSIONS.VIEW,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.VIEW,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.VIEW,
            [MODULES.STIMULATION]: PERMISSIONS.VIEW,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.VIEW,
            [MODULES.LAB_TESTS]: PERMISSIONS.VIEW,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.VIEW,
            [MODULES.RADIOLOGY]: PERMISSIONS.VIEW,
            [MODULES.ULTRASOUND]: PERMISSIONS.VIEW,
            [MODULES.PHARMACY]: PERMISSIONS.FULL,
            [MODULES.MEDICATIONS]: PERMISSIONS.FULL,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.VIEW,
            [MODULES.FINANCE]: PERMISSIONS.FULL,
            [MODULES.BILLING]: PERMISSIONS.FULL,
            [MODULES.INVOICES]: PERMISSIONS.FULL,
            [MODULES.PAYMENTS]: PERMISSIONS.FULL,
            [MODULES.INSURANCE]: PERMISSIONS.FULL,
            [MODULES.INVENTORY]: PERMISSIONS.FULL,
            [MODULES.ASSETS]: PERMISSIONS.FULL,
            [MODULES.DOCUMENTS]: PERMISSIONS.FULL,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.FULL,
            [MODULES.REPORTS]: PERMISSIONS.FULL,
            [MODULES.ANALYTICS]: PERMISSIONS.FULL,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.FULL,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.FULL,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.VIEW,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.VIEW
        }
    },
    
    [ROLES.PHYSICIAN]: {
        description: 'Primary Physician - Full clinical access',
        displayName: 'Physician',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.FULL,
            [MODULES.APPOINTMENTS]: PERMISSIONS.FULL,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.FULL,
            [MODULES.CONSULTATIONS]: PERMISSIONS.FULL,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.FULL,
            [MODULES.IVF_CYCLES]: PERMISSIONS.FULL,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.VIEW,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.VIEW,
            [MODULES.STIMULATION]: PERMISSIONS.FULL,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.VIEW,
            [MODULES.LAB_TESTS]: PERMISSIONS.FULL,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.VIEW,
            [MODULES.RADIOLOGY]: PERMISSIONS.VIEW,
            [MODULES.ULTRASOUND]: PERMISSIONS.FULL,
            [MODULES.PHARMACY]: PERMISSIONS.VIEW,
            [MODULES.MEDICATIONS]: PERMISSIONS.VIEW,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.FULL,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.VIEW,
            [MODULES.INVOICES]: PERMISSIONS.VIEW,
            [MODULES.PAYMENTS]: PERMISSIONS.NONE,
            [MODULES.INSURANCE]: PERMISSIONS.NONE,
            [MODULES.INVENTORY]: PERMISSIONS.NONE,
            [MODULES.ASSETS]: PERMISSIONS.NONE,
            [MODULES.DOCUMENTS]: PERMISSIONS.FULL,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.FULL,
            [MODULES.REPORTS]: PERMISSIONS.VIEW,
            [MODULES.ANALYTICS]: PERMISSIONS.VIEW,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.NONE
        }
    },
    
    [ROLES.IVF_SPECIALIST]: {
        description: 'IVF Specialist - Expert in IVF procedures',
        displayName: 'IVF Specialist',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.FULL,
            [MODULES.APPOINTMENTS]: PERMISSIONS.FULL,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.FULL,
            [MODULES.CONSULTATIONS]: PERMISSIONS.FULL,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.FULL,
            [MODULES.IVF_CYCLES]: PERMISSIONS.FULL,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.FULL,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.FULL,
            [MODULES.STIMULATION]: PERMISSIONS.FULL,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.VIEW,
            [MODULES.LAB_TESTS]: PERMISSIONS.FULL,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.VIEW,
            [MODULES.RADIOLOGY]: PERMISSIONS.VIEW,
            [MODULES.ULTRASOUND]: PERMISSIONS.FULL,
            [MODULES.PHARMACY]: PERMISSIONS.VIEW,
            [MODULES.MEDICATIONS]: PERMISSIONS.VIEW,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.FULL,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.VIEW,
            [MODULES.INVOICES]: PERMISSIONS.VIEW,
            [MODULES.PAYMENTS]: PERMISSIONS.NONE,
            [MODULES.INSURANCE]: PERMISSIONS.NONE,
            [MODULES.INVENTORY]: PERMISSIONS.NONE,
            [MODULES.ASSETS]: PERMISSIONS.NONE,
            [MODULES.DOCUMENTS]: PERMISSIONS.FULL,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.FULL,
            [MODULES.REPORTS]: PERMISSIONS.VIEW,
            [MODULES.ANALYTICS]: PERMISSIONS.VIEW,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.NONE
        }
    },
    
    [ROLES.PHYSICIAN_ASSISTANT]: {
        description: 'Physician Assistant - Supports physicians',
        displayName: 'Physician Assistant',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.EDIT,
            [MODULES.APPOINTMENTS]: PERMISSIONS.FULL,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.EDIT,
            [MODULES.CONSULTATIONS]: PERMISSIONS.EDIT,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.VIEW,
            [MODULES.IVF_CYCLES]: PERMISSIONS.VIEW,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.VIEW,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.VIEW,
            [MODULES.STIMULATION]: PERMISSIONS.VIEW,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.VIEW,
            [MODULES.LAB_TESTS]: PERMISSIONS.VIEW,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.VIEW,
            [MODULES.RADIOLOGY]: PERMISSIONS.VIEW,
            [MODULES.ULTRASOUND]: PERMISSIONS.VIEW,
            [MODULES.PHARMACY]: PERMISSIONS.VIEW,
            [MODULES.MEDICATIONS]: PERMISSIONS.VIEW,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.VIEW,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.NONE,
            [MODULES.INVOICES]: PERMISSIONS.NONE,
            [MODULES.PAYMENTS]: PERMISSIONS.NONE,
            [MODULES.INSURANCE]: PERMISSIONS.NONE,
            [MODULES.INVENTORY]: PERMISSIONS.NONE,
            [MODULES.ASSETS]: PERMISSIONS.NONE,
            [MODULES.DOCUMENTS]: PERMISSIONS.EDIT,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.EDIT,
            [MODULES.REPORTS]: PERMISSIONS.VIEW,
            [MODULES.ANALYTICS]: PERMISSIONS.NONE,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.NONE
        }
    },
    
    [ROLES.CLINICAL_EMBRYOLOGIST]: {
        description: 'Clinical Embryologist - Manages embryo development',
        displayName: 'Clinical Embryologist',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.VIEW,
            [MODULES.APPOINTMENTS]: PERMISSIONS.VIEW,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.VIEW,
            [MODULES.CONSULTATIONS]: PERMISSIONS.NONE,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.VIEW,
            [MODULES.IVF_CYCLES]: PERMISSIONS.EDIT,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.FULL,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.FULL,
            [MODULES.STIMULATION]: PERMISSIONS.VIEW,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.FULL,
            [MODULES.LAB_TESTS]: PERMISSIONS.FULL,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.FULL,
            [MODULES.RADIOLOGY]: PERMISSIONS.NONE,
            [MODULES.ULTRASOUND]: PERMISSIONS.NONE,
            [MODULES.PHARMACY]: PERMISSIONS.NONE,
            [MODULES.MEDICATIONS]: PERMISSIONS.NONE,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.NONE,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.NONE,
            [MODULES.INVOICES]: PERMISSIONS.NONE,
            [MODULES.PAYMENTS]: PERMISSIONS.NONE,
            [MODULES.INSURANCE]: PERMISSIONS.NONE,
            [MODULES.INVENTORY]: PERMISSIONS.VIEW,
            [MODULES.ASSETS]: PERMISSIONS.VIEW,
            [MODULES.DOCUMENTS]: PERMISSIONS.EDIT,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.VIEW,
            [MODULES.REPORTS]: PERMISSIONS.VIEW,
            [MODULES.ANALYTICS]: PERMISSIONS.VIEW,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.NONE
        }
    },
    
    [ROLES.SENIOR_EMBRYOLOGIST]: {
        description: 'Senior Embryologist - Lab supervision',
        displayName: 'Senior Embryologist',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.VIEW,
            [MODULES.APPOINTMENTS]: PERMISSIONS.VIEW,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.VIEW,
            [MODULES.CONSULTATIONS]: PERMISSIONS.NONE,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.VIEW,
            [MODULES.IVF_CYCLES]: PERMISSIONS.FULL,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.FULL,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.FULL,
            [MODULES.STIMULATION]: PERMISSIONS.VIEW,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.FULL,
            [MODULES.LAB_TESTS]: PERMISSIONS.FULL,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.FULL,
            [MODULES.RADIOLOGY]: PERMISSIONS.NONE,
            [MODULES.ULTRASOUND]: PERMISSIONS.NONE,
            [MODULES.PHARMACY]: PERMISSIONS.NONE,
            [MODULES.MEDICATIONS]: PERMISSIONS.NONE,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.NONE,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.NONE,
            [MODULES.INVOICES]: PERMISSIONS.NONE,
            [MODULES.PAYMENTS]: PERMISSIONS.NONE,
            [MODULES.INSURANCE]: PERMISSIONS.NONE,
            [MODULES.INVENTORY]: PERMISSIONS.FULL,
            [MODULES.ASSETS]: PERMISSIONS.FULL,
            [MODULES.DOCUMENTS]: PERMISSIONS.FULL,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.VIEW,
            [MODULES.REPORTS]: PERMISSIONS.FULL,
            [MODULES.ANALYTICS]: PERMISSIONS.VIEW,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.VIEW
        }
    },
    
    [ROLES.NURSE]: {
        description: 'Nurse - Patient care and assistance',
        displayName: 'Nurse',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.EDIT,
            [MODULES.APPOINTMENTS]: PERMISSIONS.FULL,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.EDIT,
            [MODULES.CONSULTATIONS]: PERMISSIONS.VIEW,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.VIEW,
            [MODULES.IVF_CYCLES]: PERMISSIONS.VIEW,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.VIEW,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.VIEW,
            [MODULES.STIMULATION]: PERMISSIONS.EDIT,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.VIEW,
            [MODULES.LAB_TESTS]: PERMISSIONS.VIEW,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.NONE,
            [MODULES.RADIOLOGY]: PERMISSIONS.VIEW,
            [MODULES.ULTRASOUND]: PERMISSIONS.VIEW,
            [MODULES.PHARMACY]: PERMISSIONS.VIEW,
            [MODULES.MEDICATIONS]: PERMISSIONS.VIEW,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.VIEW,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.NONE,
            [MODULES.INVOICES]: PERMISSIONS.NONE,
            [MODULES.PAYMENTS]: PERMISSIONS.NONE,
            [MODULES.INSURANCE]: PERMISSIONS.NONE,
            [MODULES.INVENTORY]: PERMISSIONS.VIEW,
            [MODULES.ASSETS]: PERMISSIONS.NONE,
            [MODULES.DOCUMENTS]: PERMISSIONS.EDIT,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.EDIT,
            [MODULES.REPORTS]: PERMISSIONS.VIEW,
            [MODULES.ANALYTICS]: PERMISSIONS.NONE,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.NONE
        }
    },
    
    [ROLES.NURSE_COORDINATOR]: {
        description: 'Nurse Coordinator - Coordinates patient care',
        displayName: 'Nurse Coordinator',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.FULL,
            [MODULES.APPOINTMENTS]: PERMISSIONS.FULL,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.EDIT,
            [MODULES.CONSULTATIONS]: PERMISSIONS.VIEW,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.VIEW,
            [MODULES.IVF_CYCLES]: PERMISSIONS.VIEW,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.VIEW,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.VIEW,
            [MODULES.STIMULATION]: PERMISSIONS.EDIT,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.VIEW,
            [MODULES.LAB_TESTS]: PERMISSIONS.VIEW,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.VIEW,
            [MODULES.RADIOLOGY]: PERMISSIONS.VIEW,
            [MODULES.ULTRASOUND]: PERMISSIONS.VIEW,
            [MODULES.PHARMACY]: PERMISSIONS.VIEW,
            [MODULES.MEDICATIONS]: PERMISSIONS.VIEW,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.VIEW,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.NONE,
            [MODULES.INVOICES]: PERMISSIONS.VIEW,
            [MODULES.PAYMENTS]: PERMISSIONS.NONE,
            [MODULES.INSURANCE]: PERMISSIONS.VIEW,
            [MODULES.INVENTORY]: PERMISSIONS.VIEW,
            [MODULES.ASSETS]: PERMISSIONS.NONE,
            [MODULES.DOCUMENTS]: PERMISSIONS.FULL,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.FULL,
            [MODULES.REPORTS]: PERMISSIONS.VIEW,
            [MODULES.ANALYTICS]: PERMISSIONS.VIEW,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.NONE
        }
    },
    
    [ROLES.LAB_TECHNICIAN]: {
        description: 'Lab Technician - Laboratory testing',
        displayName: 'Lab Technician',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.VIEW,
            [MODULES.APPOINTMENTS]: PERMISSIONS.NONE,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.VIEW,
            [MODULES.CONSULTATIONS]: PERMISSIONS.NONE,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.NONE,
            [MODULES.IVF_CYCLES]: PERMISSIONS.VIEW,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.VIEW,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.VIEW,
            [MODULES.STIMULATION]: PERMISSIONS.NONE,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.FULL,
            [MODULES.LAB_TESTS]: PERMISSIONS.FULL,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.FULL,
            [MODULES.RADIOLOGY]: PERMISSIONS.NONE,
            [MODULES.ULTRASOUND]: PERMISSIONS.NONE,
            [MODULES.PHARMACY]: PERMISSIONS.NONE,
            [MODULES.MEDICATIONS]: PERMISSIONS.NONE,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.NONE,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.NONE,
            [MODULES.INVOICES]: PERMISSIONS.NONE,
            [MODULES.PAYMENTS]: PERMISSIONS.NONE,
            [MODULES.INSURANCE]: PERMISSIONS.NONE,
            [MODULES.INVENTORY]: PERMISSIONS.VIEW,
            [MODULES.ASSETS]: PERMISSIONS.VIEW,
            [MODULES.DOCUMENTS]: PERMISSIONS.EDIT,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.NONE,
            [MODULES.REPORTS]: PERMISSIONS.VIEW,
            [MODULES.ANALYTICS]: PERMISSIONS.NONE,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.NONE
        }
    },
    
    [ROLES.LAB_DIRECTOR]: {
        description: 'Lab Director - Laboratory supervision',
        displayName: 'Lab Director',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.VIEW,
            [MODULES.APPOINTMENTS]: PERMISSIONS.VIEW,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.VIEW,
            [MODULES.CONSULTATIONS]: PERMISSIONS.NONE,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.NONE,
            [MODULES.IVF_CYCLES]: PERMISSIONS.VIEW,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.FULL,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.FULL,
            [MODULES.STIMULATION]: PERMISSIONS.NONE,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.FULL,
            [MODULES.LAB_TESTS]: PERMISSIONS.FULL,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.FULL,
            [MODULES.RADIOLOGY]: PERMISSIONS.NONE,
            [MODULES.ULTRASOUND]: PERMISSIONS.NONE,
            [MODULES.PHARMACY]: PERMISSIONS.NONE,
            [MODULES.MEDICATIONS]: PERMISSIONS.NONE,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.NONE,
            [MODULES.FINANCE]: PERMISSIONS.VIEW,
            [MODULES.BILLING]: PERMISSIONS.NONE,
            [MODULES.INVOICES]: PERMISSIONS.NONE,
            [MODULES.PAYMENTS]: PERMISSIONS.NONE,
            [MODULES.INSURANCE]: PERMISSIONS.NONE,
            [MODULES.INVENTORY]: PERMISSIONS.FULL,
            [MODULES.ASSETS]: PERMISSIONS.FULL,
            [MODULES.DOCUMENTS]: PERMISSIONS.FULL,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.VIEW,
            [MODULES.REPORTS]: PERMISSIONS.FULL,
            [MODULES.ANALYTICS]: PERMISSIONS.FULL,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.VIEW,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.VIEW
        }
    },
    
    [ROLES.PATHOLOGIST]: {
        description: 'Pathologist - Diagnostic analysis',
        displayName: 'Pathologist',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.VIEW,
            [MODULES.APPOINTMENTS]: PERMISSIONS.NONE,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.VIEW,
            [MODULES.CONSULTATIONS]: PERMISSIONS.NONE,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.NONE,
            [MODULES.IVF_CYCLES]: PERMISSIONS.VIEW,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.VIEW,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.NONE,
            [MODULES.STIMULATION]: PERMISSIONS.NONE,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.FULL,
            [MODULES.LAB_TESTS]: PERMISSIONS.FULL,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.FULL,
            [MODULES.RADIOLOGY]: PERMISSIONS.NONE,
            [MODULES.ULTRASOUND]: PERMISSIONS.NONE,
            [MODULES.PHARMACY]: PERMISSIONS.NONE,
            [MODULES.MEDICATIONS]: PERMISSIONS.NONE,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.NONE,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.NONE,
            [MODULES.INVOICES]: PERMISSIONS.NONE,
            [MODULES.PAYMENTS]: PERMISSIONS.NONE,
            [MODULES.INSURANCE]: PERMISSIONS.NONE,
            [MODULES.INVENTORY]: PERMISSIONS.VIEW,
            [MODULES.ASSETS]: PERMISSIONS.VIEW,
            [MODULES.DOCUMENTS]: PERMISSIONS.FULL,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.NONE,
            [MODULES.REPORTS]: PERMISSIONS.FULL,
            [MODULES.ANALYTICS]: PERMISSIONS.VIEW,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.NONE
        }
    },
    
    [ROLES.RADIOLOGIST]: {
        description: 'Radiologist - Imaging interpretation',
        displayName: 'Radiologist',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.VIEW,
            [MODULES.APPOINTMENTS]: PERMISSIONS.VIEW,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.VIEW,
            [MODULES.CONSULTATIONS]: PERMISSIONS.NONE,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.NONE,
            [MODULES.IVF_CYCLES]: PERMISSIONS.VIEW,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.NONE,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.NONE,
            [MODULES.STIMULATION]: PERMISSIONS.VIEW,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.LAB_TESTS]: PERMISSIONS.VIEW,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.NONE,
            [MODULES.RADIOLOGY]: PERMISSIONS.FULL,
            [MODULES.ULTRASOUND]: PERMISSIONS.FULL,
            [MODULES.PHARMACY]: PERMISSIONS.NONE,
            [MODULES.MEDICATIONS]: PERMISSIONS.NONE,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.NONE,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.NONE,
            [MODULES.INVOICES]: PERMISSIONS.NONE,
            [MODULES.PAYMENTS]: PERMISSIONS.NONE,
            [MODULES.INSURANCE]: PERMISSIONS.NONE,
            [MODULES.INVENTORY]: PERMISSIONS.VIEW,
            [MODULES.ASSETS]: PERMISSIONS.VIEW,
            [MODULES.DOCUMENTS]: PERMISSIONS.FULL,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.NONE,
            [MODULES.REPORTS]: PERMISSIONS.FULL,
            [MODULES.ANALYTICS]: PERMISSIONS.VIEW,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.NONE
        }
    },
    
    [ROLES.RADIOLOGY_TECHNICIAN]: {
        description: 'Radiology Technician - Performs imaging',
        displayName: 'Radiology Technician',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.VIEW,
            [MODULES.APPOINTMENTS]: PERMISSIONS.VIEW,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.VIEW,
            [MODULES.CONSULTATIONS]: PERMISSIONS.NONE,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.NONE,
            [MODULES.IVF_CYCLES]: PERMISSIONS.VIEW,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.NONE,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.NONE,
            [MODULES.STIMULATION]: PERMISSIONS.NONE,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.LAB_TESTS]: PERMISSIONS.NONE,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.NONE,
            [MODULES.RADIOLOGY]: PERMISSIONS.EDIT,
            [MODULES.ULTRASOUND]: PERMISSIONS.EDIT,
            [MODULES.PHARMACY]: PERMISSIONS.NONE,
            [MODULES.MEDICATIONS]: PERMISSIONS.NONE,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.NONE,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.NONE,
            [MODULES.INVOICES]: PERMISSIONS.NONE,
            [MODULES.PAYMENTS]: PERMISSIONS.NONE,
            [MODULES.INSURANCE]: PERMISSIONS.NONE,
            [MODULES.INVENTORY]: PERMISSIONS.NONE,
            [MODULES.ASSETS]: PERMISSIONS.VIEW,
            [MODULES.DOCUMENTS]: PERMISSIONS.EDIT,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.NONE,
            [MODULES.REPORTS]: PERMISSIONS.VIEW,
            [MODULES.ANALYTICS]: PERMISSIONS.NONE,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.NONE
        }
    },
    
    [ROLES.RECEPTIONIST]: {
        description: 'Receptionist - Front desk operations',
        displayName: 'Receptionist',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.FULL,
            [MODULES.APPOINTMENTS]: PERMISSIONS.FULL,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.NONE,
            [MODULES.CONSULTATIONS]: PERMISSIONS.NONE,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.NONE,
            [MODULES.IVF_CYCLES]: PERMISSIONS.NONE,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.NONE,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.NONE,
            [MODULES.STIMULATION]: PERMISSIONS.NONE,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.LAB_TESTS]: PERMISSIONS.NONE,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.NONE,
            [MODULES.RADIOLOGY]: PERMISSIONS.NONE,
            [MODULES.ULTRASOUND]: PERMISSIONS.NONE,
            [MODULES.PHARMACY]: PERMISSIONS.NONE,
            [MODULES.MEDICATIONS]: PERMISSIONS.NONE,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.NONE,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.FULL,
            [MODULES.INVOICES]: PERMISSIONS.FULL,
            [MODULES.PAYMENTS]: PERMISSIONS.FULL,
            [MODULES.INSURANCE]: PERMISSIONS.VIEW,
            [MODULES.INVENTORY]: PERMISSIONS.NONE,
            [MODULES.ASSETS]: PERMISSIONS.NONE,
            [MODULES.DOCUMENTS]: PERMISSIONS.EDIT,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.EDIT,
            [MODULES.REPORTS]: PERMISSIONS.NONE,
            [MODULES.ANALYTICS]: PERMISSIONS.NONE,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.NONE
        }
    },
    
    [ROLES.PATIENT_COORDINATOR]: {
        description: 'Patient Coordinator - Patient journey management',
        displayName: 'Patient Coordinator',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.FULL,
            [MODULES.APPOINTMENTS]: PERMISSIONS.FULL,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.VIEW,
            [MODULES.CONSULTATIONS]: PERMISSIONS.VIEW,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.VIEW,
            [MODULES.IVF_CYCLES]: PERMISSIONS.VIEW,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.NONE,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.NONE,
            [MODULES.STIMULATION]: PERMISSIONS.NONE,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.LAB_TESTS]: PERMISSIONS.VIEW,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.NONE,
            [MODULES.RADIOLOGY]: PERMISSIONS.NONE,
            [MODULES.ULTRASOUND]: PERMISSIONS.NONE,
            [MODULES.PHARMACY]: PERMISSIONS.NONE,
            [MODULES.MEDICATIONS]: PERMISSIONS.NONE,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.VIEW,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.FULL,
            [MODULES.INVOICES]: PERMISSIONS.FULL,
            [MODULES.PAYMENTS]: PERMISSIONS.FULL,
            [MODULES.INSURANCE]: PERMISSIONS.VIEW,
            [MODULES.INVENTORY]: PERMISSIONS.NONE,
            [MODULES.ASSETS]: PERMISSIONS.NONE,
            [MODULES.DOCUMENTS]: PERMISSIONS.FULL,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.FULL,
            [MODULES.REPORTS]: PERMISSIONS.VIEW,
            [MODULES.ANALYTICS]: PERMISSIONS.NONE,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.NONE
        }
    },
    
    [ROLES.FINANCE_MANAGER]: {
        description: 'Finance Manager - Financial operations management',
        displayName: 'Finance Manager',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.VIEW,
            [MODULES.APPOINTMENTS]: PERMISSIONS.NONE,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.NONE,
            [MODULES.CONSULTATIONS]: PERMISSIONS.NONE,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.NONE,
            [MODULES.IVF_CYCLES]: PERMISSIONS.NONE,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.NONE,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.NONE,
            [MODULES.STIMULATION]: PERMISSIONS.NONE,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.LAB_TESTS]: PERMISSIONS.NONE,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.NONE,
            [MODULES.RADIOLOGY]: PERMISSIONS.NONE,
            [MODULES.ULTRASOUND]: PERMISSIONS.NONE,
            [MODULES.PHARMACY]: PERMISSIONS.VIEW,
            [MODULES.MEDICATIONS]: PERMISSIONS.VIEW,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.NONE,
            [MODULES.FINANCE]: PERMISSIONS.FULL,
            [MODULES.BILLING]: PERMISSIONS.FULL,
            [MODULES.INVOICES]: PERMISSIONS.FULL,
            [MODULES.PAYMENTS]: PERMISSIONS.FULL,
            [MODULES.INSURANCE]: PERMISSIONS.FULL,
            [MODULES.INVENTORY]: PERMISSIONS.VIEW,
            [MODULES.ASSETS]: PERMISSIONS.FULL,
            [MODULES.DOCUMENTS]: PERMISSIONS.VIEW,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.NONE,
            [MODULES.REPORTS]: PERMISSIONS.FULL,
            [MODULES.ANALYTICS]: PERMISSIONS.FULL,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.VIEW,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.VIEW
        }
    },
    
    [ROLES.BILLING_SPECIALIST]: {
        description: 'Billing Specialist - Handles billing operations',
        displayName: 'Billing Specialist',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.VIEW,
            [MODULES.APPOINTMENTS]: PERMISSIONS.NONE,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.NONE,
            [MODULES.CONSULTATIONS]: PERMISSIONS.NONE,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.VIEW,
            [MODULES.IVF_CYCLES]: PERMISSIONS.VIEW,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.NONE,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.NONE,
            [MODULES.STIMULATION]: PERMISSIONS.NONE,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.LAB_TESTS]: PERMISSIONS.NONE,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.NONE,
            [MODULES.RADIOLOGY]: PERMISSIONS.NONE,
            [MODULES.ULTRASOUND]: PERMISSIONS.NONE,
            [MODULES.PHARMACY]: PERMISSIONS.NONE,
            [MODULES.MEDICATIONS]: PERMISSIONS.NONE,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.NONE,
            [MODULES.FINANCE]: PERMISSIONS.VIEW,
            [MODULES.BILLING]: PERMISSIONS.FULL,
            [MODULES.INVOICES]: PERMISSIONS.FULL,
            [MODULES.PAYMENTS]: PERMISSIONS.FULL,
            [MODULES.INSURANCE]: PERMISSIONS.FULL,
            [MODULES.INVENTORY]: PERMISSIONS.NONE,
            [MODULES.ASSETS]: PERMISSIONS.NONE,
            [MODULES.DOCUMENTS]: PERMISSIONS.VIEW,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.NONE,
            [MODULES.REPORTS]: PERMISSIONS.VIEW,
            [MODULES.ANALYTICS]: PERMISSIONS.NONE,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.NONE
        }
    },
    
    [ROLES.PHARMACIST]: {
        description: 'Pharmacist - Medication management',
        displayName: 'Pharmacist',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.VIEW,
            [MODULES.APPOINTMENTS]: PERMISSIONS.NONE,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.VIEW,
            [MODULES.CONSULTATIONS]: PERMISSIONS.NONE,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.VIEW,
            [MODULES.IVF_CYCLES]: PERMISSIONS.VIEW,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.NONE,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.NONE,
            [MODULES.STIMULATION]: PERMISSIONS.VIEW,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.LAB_TESTS]: PERMISSIONS.NONE,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.NONE,
            [MODULES.RADIOLOGY]: PERMISSIONS.NONE,
            [MODULES.ULTRASOUND]: PERMISSIONS.NONE,
            [MODULES.PHARMACY]: PERMISSIONS.FULL,
            [MODULES.MEDICATIONS]: PERMISSIONS.FULL,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.FULL,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.VIEW,
            [MODULES.INVOICES]: PERMISSIONS.VIEW,
            [MODULES.PAYMENTS]: PERMISSIONS.NONE,
            [MODULES.INSURANCE]: PERMISSIONS.NONE,
            [MODULES.INVENTORY]: PERMISSIONS.FULL,
            [MODULES.ASSETS]: PERMISSIONS.NONE,
            [MODULES.DOCUMENTS]: PERMISSIONS.EDIT,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.NONE,
            [MODULES.REPORTS]: PERMISSIONS.VIEW,
            [MODULES.ANALYTICS]: PERMISSIONS.NONE,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.NONE
        }
    },
    
    [ROLES.QUALITY_MANAGER]: {
        description: 'Quality Manager - Quality assurance and compliance',
        displayName: 'Quality Manager',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.VIEW,
            [MODULES.APPOINTMENTS]: PERMISSIONS.VIEW,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.VIEW,
            [MODULES.CONSULTATIONS]: PERMISSIONS.VIEW,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.VIEW,
            [MODULES.IVF_CYCLES]: PERMISSIONS.VIEW,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.VIEW,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.VIEW,
            [MODULES.STIMULATION]: PERMISSIONS.VIEW,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.VIEW,
            [MODULES.LAB_TESTS]: PERMISSIONS.VIEW,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.VIEW,
            [MODULES.RADIOLOGY]: PERMISSIONS.VIEW,
            [MODULES.ULTRASOUND]: PERMISSIONS.VIEW,
            [MODULES.PHARMACY]: PERMISSIONS.VIEW,
            [MODULES.MEDICATIONS]: PERMISSIONS.VIEW,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.VIEW,
            [MODULES.FINANCE]: PERMISSIONS.VIEW,
            [MODULES.BILLING]: PERMISSIONS.VIEW,
            [MODULES.INVOICES]: PERMISSIONS.VIEW,
            [MODULES.PAYMENTS]: PERMISSIONS.VIEW,
            [MODULES.INSURANCE]: PERMISSIONS.VIEW,
            [MODULES.INVENTORY]: PERMISSIONS.VIEW,
            [MODULES.ASSETS]: PERMISSIONS.VIEW,
            [MODULES.DOCUMENTS]: PERMISSIONS.FULL,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.FULL,
            [MODULES.REPORTS]: PERMISSIONS.FULL,
            [MODULES.ANALYTICS]: PERMISSIONS.FULL,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.FULL
        }
    },
    
    [ROLES.FERTILITY_COUNSELOR]: {
        description: 'Fertility Counselor - Patient counseling',
        displayName: 'Fertility Counselor',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.VIEW,
            [MODULES.APPOINTMENTS]: PERMISSIONS.FULL,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.VIEW,
            [MODULES.CONSULTATIONS]: PERMISSIONS.EDIT,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.VIEW,
            [MODULES.IVF_CYCLES]: PERMISSIONS.VIEW,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.NONE,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.NONE,
            [MODULES.STIMULATION]: PERMISSIONS.NONE,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.LAB_TESTS]: PERMISSIONS.NONE,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.NONE,
            [MODULES.RADIOLOGY]: PERMISSIONS.NONE,
            [MODULES.ULTRASOUND]: PERMISSIONS.NONE,
            [MODULES.PHARMACY]: PERMISSIONS.NONE,
            [MODULES.MEDICATIONS]: PERMISSIONS.NONE,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.NONE,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.NONE,
            [MODULES.INVOICES]: PERMISSIONS.NONE,
            [MODULES.PAYMENTS]: PERMISSIONS.NONE,
            [MODULES.INSURANCE]: PERMISSIONS.NONE,
            [MODULES.INVENTORY]: PERMISSIONS.NONE,
            [MODULES.ASSETS]: PERMISSIONS.NONE,
            [MODULES.DOCUMENTS]: PERMISSIONS.EDIT,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.EDIT,
            [MODULES.REPORTS]: PERMISSIONS.NONE,
            [MODULES.ANALYTICS]: PERMISSIONS.NONE,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.NONE,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.NONE,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.NONE
        }
    },
    
    [ROLES.IT_ADMIN]: {
        description: 'IT Administrator - Technical support',
        displayName: 'IT Administrator',
        modules: {
            [MODULES.DASHBOARD]: PERMISSIONS.VIEW,
            [MODULES.PATIENTS]: PERMISSIONS.NONE,
            [MODULES.APPOINTMENTS]: PERMISSIONS.NONE,
            [MODULES.MEDICAL_RECORDS]: PERMISSIONS.NONE,
            [MODULES.CONSULTATIONS]: PERMISSIONS.NONE,
            [MODULES.TREATMENT_PLANS]: PERMISSIONS.NONE,
            [MODULES.IVF_CYCLES]: PERMISSIONS.NONE,
            [MODULES.EMBRYOLOGY]: PERMISSIONS.NONE,
            [MODULES.CRYOPRESERVATION]: PERMISSIONS.NONE,
            [MODULES.STIMULATION]: PERMISSIONS.NONE,
            [MODULES.LAB_MANAGEMENT]: PERMISSIONS.NONE,
            [MODULES.LAB_TESTS]: PERMISSIONS.NONE,
            [MODULES.SEMEN_ANALYSIS]: PERMISSIONS.NONE,
            [MODULES.RADIOLOGY]: PERMISSIONS.NONE,
            [MODULES.ULTRASOUND]: PERMISSIONS.NONE,
            [MODULES.PHARMACY]: PERMISSIONS.NONE,
            [MODULES.MEDICATIONS]: PERMISSIONS.NONE,
            [MODULES.PRESCRIPTIONS]: PERMISSIONS.NONE,
            [MODULES.FINANCE]: PERMISSIONS.NONE,
            [MODULES.BILLING]: PERMISSIONS.NONE,
            [MODULES.INVOICES]: PERMISSIONS.NONE,
            [MODULES.PAYMENTS]: PERMISSIONS.NONE,
            [MODULES.INSURANCE]: PERMISSIONS.NONE,
            [MODULES.INVENTORY]: PERMISSIONS.VIEW,
            [MODULES.ASSETS]: PERMISSIONS.FULL,
            [MODULES.DOCUMENTS]: PERMISSIONS.VIEW,
            [MODULES.CONSENT_FORMS]: PERMISSIONS.NONE,
            [MODULES.REPORTS]: PERMISSIONS.VIEW,
            [MODULES.ANALYTICS]: PERMISSIONS.VIEW,
            [MODULES.USER_MANAGEMENT]: PERMISSIONS.FULL,
            [MODULES.CLINIC_SETTINGS]: PERMISSIONS.EDIT,
            [MODULES.SUBSCRIPTION]: PERMISSIONS.VIEW,
            [MODULES.AUDIT_LOGS]: PERMISSIONS.FULL
        }
    }
};

// Helper function to check if role has permission for module
const hasPermission = (role, module, requiredPermission) => {
    const roleConfig = ROLE_PERMISSIONS[role];
    if (!roleConfig) return false;
    
    const modulePermission = roleConfig.modules[module];
    if (!modulePermission || modulePermission === PERMISSIONS.NONE) return false;
    
    // Full permission grants everything
    if (modulePermission === PERMISSIONS.FULL) return true;
    
    // Check specific permissions
    // VIEW permission is granted if user has VIEW, EDIT, or FULL access
    if (requiredPermission === PERMISSIONS.VIEW) {
        return [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.FULL].includes(modulePermission);
    }
    // EDIT permission is granted only if user has EDIT or FULL access
    if (requiredPermission === PERMISSIONS.EDIT) {
        return [PERMISSIONS.EDIT, PERMISSIONS.FULL].includes(modulePermission);
    }
    // CREATE permission is granted only if user has CREATE or FULL access
    if (requiredPermission === PERMISSIONS.CREATE) {
        return [PERMISSIONS.CREATE, PERMISSIONS.FULL].includes(modulePermission);
    }
    // DELETE permission is granted only if user has DELETE or FULL access
    if (requiredPermission === PERMISSIONS.DELETE) {
        return [PERMISSIONS.DELETE, PERMISSIONS.FULL].includes(modulePermission);
    }
    
    return modulePermission === requiredPermission;
};

// Get all roles as array for dropdown/select
const getAllRoles = () => {
    return Object.keys(ROLE_PERMISSIONS).map(role => ({
        value: role,
        label: ROLE_PERMISSIONS[role].displayName,
        description: ROLE_PERMISSIONS[role].description
    }));
};

// Get modules for a specific role
const getModulesForRole = (role) => {
    const roleConfig = ROLE_PERMISSIONS[role];
    if (!roleConfig) return [];
    
    return Object.entries(roleConfig.modules)
        .filter(([_, permission]) => permission !== PERMISSIONS.NONE)
        .map(([module, permission]) => ({
            module,
            permission
        }));
};

// Check if role is admin level
const isAdminRole = (role) => {
    return [ROLES.OWNER, ROLES.ADMIN].includes(role);
};

// Check if role is clinical
const isClinicalRole = (role) => {
    return [
        ROLES.PHYSICIAN,
        ROLES.PHYSICIAN_ASSISTANT,
        ROLES.IVF_SPECIALIST,
        ROLES.NURSE,
        ROLES.NURSE_COORDINATOR
    ].includes(role);
};

module.exports = {
    ROLES,
    MODULES,
    PERMISSIONS,
    ROLE_PERMISSIONS,
    hasPermission,
    getAllRoles,
    getModulesForRole,
    isAdminRole,
    isClinicalRole
};
